"""user-progress  model added

Revision ID: b6a7c52d487c
Revises: 7b4012355d2a
Create Date: 2026-07-05 15:48:19.275274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6a7c52d487c'
down_revision: Union[str, Sequence[str], None] = '7b4012355d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_conversations', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('average_score', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('current_streak', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('longest_streak', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_conversation_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_progress')
    # ### end Alembic commands ###
